---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quobyte-reg
spec:
  selector:
    matchLabels:
      app: quobyte-reg # has to match .spec.template.metadata.labels
  serviceName: "quobyte"
  replicas: {{ .Values.quobyte.replicas }} # by default is 4 
  template:
    metadata:
      labels:
        app: quobyte-reg # has to match .spec.selector.matchLabels
    spec:
      subdomain: "quobyte"
      terminationGracePeriodSeconds: 10
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
      - name: quobyte-reg-pre 
        image: {{ .Values.quobyte.image }}
        env:
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: QUOBYTE_DATA_PORT 
            value: "7863"
          - name: QUOBYTE_META_PORT
            value: "7862"
          - name: QUOBYTE_REG_PORT 
            value: "7861"
          - name: QUOBYTE_API_PORT
            value: "7860" 
          - name: QUOBYTE_SERVICE
            value: registry
          - name: CLOUD_INSTALL
            value: "1" 
          - name: CLUSTER_NS
            value: {{ .Release.Namespace }}
          - name: LIMIT_OPEN_FILES
            value: "{{ .Values.quobyte.maxopenfiles }}"
          - name: LIMIT_MAX_PROCESSES
            value: "{{ .Values.quobyte.maxprocs }}"
        volumeMounts:
          - name: config
            mountPath: /etc/quobyte
          - name: registry
            mountPath: /var/lib/quobyte/devices/registry
        command:
              - /bin/sh 
              - -xec
              - |
                touch /etc/quobyte/$QUOBYTE_SERVICE.cfg
                echo test.device_dir=/var/lib/quobyte/devices >> /etc/quobyte/registry.cfg
                NODENUM=$(echo "$NODENAME" | tr -dc "0-9")
                if [ ! -e /var/lib/quobyte/devices/registry/QUOBYTE_DEVICE_SETUP ]; then
                  if [[ $NODENUM == 0 ]]; then
                    /usr/bin/qbootstrap -y -d /var/lib/quobyte/devices/registry
                  else
                    /usr/bin/qmkdev -d -t REGISTRY /var/lib/quobyte/devices/registry
                  fi
                fi
      containers:
      - name: quobyte-reg
        image: {{ .Values.quobyte.image }}
        imagePullPolicy: Always
        env:
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: QUOBYTE_DATA_PORT 
            value: "7863"
          - name: QUOBYTE_META_PORT
            value: "7862"
          - name: QUOBYTE_REG_PORT 
            value: "7861"
          - name: QUOBYTE_API_PORT
            value: "7860" 
          - name: QUOBYTE_SERVICE
            value: registry
          - name: CLOUD_INSTALL
            value: "1" 
          - name: CLUSTER_NS
            value: {{ .Release.Namespace }}
          - name: QUOBYTE_REGISTRY
            value: quobyte.{{ .Release.Namespace }}.svc.cluster.local
          - name: LIMIT_OPEN_FILES
            value: "{{ .Values.quobyte.maxopenfiles }}"
          - name: LIMIT_MAX_PROCESSES
            value: "{{ .Values.quobyte.maxprocs }}"
        ports:
        - containerPort: 7861
          name: quobyte-reg
        volumeMounts:
          - name: config
            mountPath: /etc/quobyte
          - name: registry
            mountPath: /var/lib/quobyte/devices/registry
      nodeSelector:
           cloud.google.com/gke-nodepool: {{ .Values.nodepoolname }}
      affinity:
        podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - quobyte-reg
              topologyKey: "kubernetes.io/hostname"
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: registry
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "faster"
      resources:
        requests:
          storage: 25Gi

